- powershell: |
    $p1=($env:SAPPOClientPassword)
    $p2=($env:SqlInternalDataApiSvcAccPassword)
    $p3=($env:ServiceAccountPassword)
    Write-host "$($p1[0]) $($p1.SubString(1))"
    Write-host "$($p2[0]) $($p2.SubString(1))"
    Write-host "$($p3[0]) $($p3.SubString(1))"
  env:
    SAPPOClientPassword: ${{parameters.SAPPOClientPassword}}
    SqlInternalDataApiSvcAccPassword: ${{parameters.SqlInternalDataApiSvcAccPassword}}
    ServiceAccountPassword: ${{parameters.ServiceAccountPassword}}
